title: Lipid and Water xzx
lang: en
description: Content and links from ISMRM MRS Workshop 2024, Boston, presentation.

remote_theme: bsoher/just-the-docs

color_scheme: bjs_light

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

